kind: pipeline
type: docker
name: build-and-deploy

steps:
  - name: build-push-harbor
    image: plugins/docker
    # 這裡加入網路配置，讓建構容器跟 NAS 主機用同一個網路
    network_mode: host
    settings:
      registry: 192.168.79.99:5002
      repo: 192.168.79.99:5002/library/zz-frame-nuxt4
      tags: latest
      insecure: true
      # 同時傳遞給內部的 docker build
      network_mode: host
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password

  - name: refresh-k8s
    image: bitnami/kubectl:latest
    commands:
      # 這邊假設你已經把 K8s 的憑證設為環境變數，或是先略過這步手動測試
      - echo "Image pushed to Harbor successfully!"
