kind: pipeline
type: docker
name: deploy-nuxt

steps:
  # 第一步：直接用 node 鏡像下載套件（測試是否能通）
  - name: install-deps
    image: node:20-alpine
    # 這裡關鍵：強迫這個步驟用 host 網路
    commands:
      - npm config set registry https://registry.npmmirror.com
      - npm install

  - name: build-push-harbor
    image: plugins/docker
    # 這裡加入網路配置，讓建構容器跟 NAS 主機用同一個網路
    settings:
      registry: 192.168.79.99:5002
      repo: 192.168.79.99:5002/library/zz-frame-nuxt4
      tags: latest
      insecure: true # 這是因為我們 Harbor 用的是 HTTP
      privileged: true # 配合你剛才勾選的 Trusted
      # custom_dns: [192.168.69.1, 192.168.171.43]
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password

  - name: deploy-to-k8s
    image: appleboy/drone-ssh
    settings:
      host: 192.168.79.100
      username: zz # 你的 K8s 帳號
      key:
        from_secret: ssh_key # 在 Drone 介面設定 SSH 私鑰
      script:
        # 強制 K8s 重新拉取最新鏡像並滾動更新
        - kubectl rollout restart deployment/zz-frame-nuxt4

trigger:
  branch:
    - main
