apiVersion: apps/v1
kind: Deployment
metadata:
  name: zz-frame-nuxt4
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zz-frame-nuxt4
  template:
    metadata:
      labels:
        app: zz-frame-nuxt4
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: nuxt-app
          image: 192.168.79.99:5002/library/zz-frame-nuxt4:latest
          imagePullPolicy: Always # 確保每次重啟都會去 Harbor 拉最新版
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: zz-frame-dep-secret
          volumeMounts:
            - name: uploads
              mountPath: /uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zz-frame-nuxt4-svc
spec:
  selector:
    app: zz-frame-nuxt4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 100Gi # 宣告容量大小
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # 允許多個 Pod 同時讀寫
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/kubernetes # NAS 上的實際路徑
    server: 192.168.79.99 # NAS IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
