apiVersion: v1
kind: Service
metadata:
  labels:
    app: zz-frame-test
  name: zz-frame-nodeport-test
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 30080
  selector:
    app: zz-frame-test
status:
  loadBalancer: {}
