apiVersion: v1
kind: Service
metadata:
  labels:
    app: zz-frame-test
  name: zz-frame-test
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: zz-frame-test
  type: ClusterIP
status:
  loadBalancer: {}
