apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nuxt3-test-cert
spec:
  secretName: nuxt3-test-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - nuxt.cdc.internal
